"""add_category_fields_to_transactions

Revision ID: 0a5aca0de52d
Revises: 38293e7c76c7
Create Date: 2026-07-30 18:27:40.551346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a5aca0de52d'
down_revision: Union[str, None] = '38293e7c76c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('category', sa.String(length=64), nullable=True))
    op.add_column('transactions', sa.Column('confidence_score', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('matched_rule', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'matched_rule')
    op.drop_column('transactions', 'confidence_score')
    op.drop_column('transactions', 'category')
    # ### end Alembic commands ###
