"""create_transactions_table

Revision ID: 38293e7c76c7
Revises: f39e2947f2c5
Create Date: 2026-07-30 18:16:39.559609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38293e7c76c7'
down_revision: Union[str, None] = 'f39e2947f2c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('statement_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.String(length=16), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('transaction_type', sa.String(length=8), nullable=False),
    sa.Column('merchant', sa.String(length=255), nullable=True),
    sa.Column('payment_mode', sa.String(length=32), nullable=True),
    sa.Column('reference_number', sa.String(length=128), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['statement_id'], ['statements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_statement_id'), 'transactions', ['statement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_statement_id'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
