CATEGORIES = [
    "Food", "Groceries", "Shopping", "Fuel", "Travel",
    "Bills", "Entertainment", "Healthcare", "Education",
    "Salary", "Investment", "Rent", "Transfer", "ATM", "Others",
]

# (pattern, category, confidence, is_merchant)
RULES: list[tuple[str, str, int, bool]] = [
    # ── Food ──────────────────────────────────────────────
    ("zomato", "Food", 95, True),
    ("swiggy", "Food", 95, True),
    ("dominos", "Food", 95, True),
    ("domino's", "Food", 95, True),
    ("pizza hut", "Food", 95, True),
    ("mcdonalds", "Food", 95, True),
    ("mcdonald's", "Food", 95, True),
    ("kfc", "Food", 95, True),
    ("subway", "Food", 92, True),
    ("subway", "Food", 92, True),
    ("burger king", "Food", 95, True),
    ("starbucks", "Food", 93, True),
    ("cafe coffee day", "Food", 92, True),
    ("ccd", "Food", 88, True),
    ("dunkin", "Food", 90, True),
    ("faasos", "Food", 92, True),
    ("box8", "Food", 92, True),
    ("eatfit", "Food", 92, True),
    ("freshmenu", "Food", 92, True),
    ("uber eats", "Food", 93, True),
    ("foodpanda", "Food", 93, True),
    ("zepto cafe", "Food", 85, True),
    ("pind", "Food", 88, True),
    ("behrouz", "Food", 90, True),
    ("lunchbox", "Food", 85, True),
    ("momos", "Food", 80, False),
    ("restaurant", "Food", 75, False),
    ("cafe", "Food", 75, False),
    ("hotel", "Food", 70, False),
    ("food", "Food", 70, False),
    ("dining", "Food", 75, False),
    ("bakery", "Food", 80, False),
    ("pizza", "Food", 85, False),
    ("burger", "Food", 85, False),
    ("biryani", "Food", 85, False),
    ("tiffin", "Food", 80, False),

    # ── Groceries ─────────────────────────────────────────
    ("dmart", "Groceries", 95, True),
    ("bigbasket", "Groceries", 95, True),
    ("grofers", "Groceries", 95, True),
    ("blinkit", "Groceries", 92, True),
    ("zepto", "Groceries", 90, True),
    ("jio mart", "Groceries", 90, True),
    ("jiomart", "Groceries", 90, True),
    ("amazon fresh", "Groceries", 92, True),
    ("fresh to home", "Groceries", 90, True),
    ("milkbasket", "Groceries", 92, True),
    ("natures basket", "Groceries", 90, True),
    ("nature's basket", "Groceries", 90, True),
    ("spencers", "Groceries", 88, True),
    ("spencer's", "Groceries", 88, True),
    ("reliance fresh", "Groceries", 88, True),
    ("more supermarket", "Groceries", 85, True),
    ("star market", "Groceries", 85, True),
    ("grocery", "Groceries", 75, False),
    ("groceries", "Groceries", 80, False),
    ("supermarket", "Groceries", 78, False),
    ("vegetables", "Groceries", 75, False),
    ("fruits", "Groceries", 75, False),
    ("milk", "Groceries", 70, False),
    ("daily needs", "Groceries", 72, False),

    # ── Shopping ──────────────────────────────────────────
    ("amazon", "Shopping", 90, True),
    ("flipkart", "Shopping", 95, True),
    ("myntra", "Shopping", 95, True),
    ("ajio", "Shopping", 93, True),
    ("zara", "Shopping", 90, True),
    ("h&m", "Shopping", 90, True),
    ("uniqlo", "Shopping", 90, True),
    ("puma", "Shopping", 90, True),
    ("adidas", "Shopping", 90, True),
    ("nike", "Shopping", 90, True),
    ("decathlon", "Shopping", 92, True),
    ("reliance trends", "Shopping", 88, True),
    ("shoppers stop", "Shopping", 88, True),
    ("shopper's stop", "Shopping", 88, True),
    ("croma", "Shopping", 92, True),
    ("vijay sales", "Shopping", 88, True),
    ("tata cliq", "Shopping", 90, True),
    ("tatacliq", "Shopping", 90, True),
    ("meesho", "Shopping", 90, True),
    ("shopclues", "Shopping", 85, True),
    ("snapdeal", "Shopping", 85, True),
    ("nykaa", "Shopping", 93, True),
    ("purplle", "Shopping", 88, True),
    ("maccaron", "Shopping", 85, True),
    ("tira", "Shopping", 82, True),
    ("lenskart", "Shopping", 92, True),
    ("pepperfry", "Shopping", 88, True),
    ("urban ladder", "Shopping", 88, True),
    ("shopping", "Shopping", 70, False),
    ("clothing", "Shopping", 75, False),
    ("apparel", "Shopping", 75, False),
    ("electronics", "Shopping", 75, False),
    ("mobile", "Shopping", 70, False),

    # ── Fuel ──────────────────────────────────────────────
    ("indian oil", "Fuel", 95, True),
    ("iocl", "Fuel", 95, True),
    ("bpcl", "Fuel", 95, True),
    ("bharat petroleum", "Fuel", 95, True),
    ("hpcl", "Fuel", 95, True),
    ("hindu petroleum", "Fuel", 95, True),
    ("shell", "Fuel", 93, True),
    ("petrol", "Fuel", 90, False),
    ("diesel", "Fuel", 90, False),
    ("fuel", "Fuel", 85, False),
    ("bunk", "Fuel", 80, False),
    ("gas station", "Fuel", 85, False),
    ("cng", "Fuel", 85, False),

    # ── Travel ────────────────────────────────────────────
    ("irctc", "Travel", 95, True),
    ("goibibo", "Travel", 95, True),
    ("makemytrip", "Travel", 95, True),
    ("make my trip", "Travel", 95, True),
    ("yatra", "Travel", 93, True),
    ("cleartrip", "Travel", 93, True),
    ("ixigo", "Travel", 92, True),
    ("oyo", "Travel", 92, True),
    ("booking.com", "Travel", 90, True),
    ("expedia", "Travel", 90, True),
    ("agoda", "Travel", 88, True),
    ("uber", "Travel", 90, True),
    ("ola", "Travel", 90, True),
    ("rapido", "Travel", 88, True),
    ("meru", "Travel", 88, True),
    ("indigo", "Travel", 92, True),
    ("spicejet", "Travel", 92, True),
    ("spice jet", "Travel", 92, True),
    ("air india", "Travel", 92, True),
    ("vistara", "Travel", 92, True),
    ("goair", "Travel", 88, True),
    ("redbus", "Travel", 93, True),
    ("red bus", "Travel", 93, True),
    ("abhibus", "Travel", 88, True),
    ("paytm bus", "Travel", 85, True),
    ("bus", "Travel", 75, False),
    ("train", "Travel", 75, False),
    ("flight", "Travel", 80, False),
    ("taxi", "Travel", 78, False),
    ("cab", "Travel", 75, False),
    ("metro", "Travel", 78, False),
    ("toll", "Travel", 70, False),
    ("parking", "Travel", 70, False),
    ("hotel", "Travel", 65, False),
    ("travel", "Travel", 70, False),
    ("holiday", "Travel", 72, False),
    ("trip", "Travel", 70, False),

    # ── Bills ─────────────────────────────────────────────
    ("airtel", "Bills", 88, True),
    ("jio", "Bills", 88, True),
    ("vi", "Bills", 88, True),
    ("vodafone", "Bills", 88, True),
    ("idea", "Bills", 88, True),
    ("tata play", "Bills", 88, True),
    ("tata sky", "Bills", 88, True),
    ("dish tv", "Bills", 88, True),
    ("netflix", "Bills", 85, True),
    ("broadband", "Bills", 85, False),
    ("wifi", "Bills", 80, False),
    ("electricity", "Bills", 88, False),
    ("electricity bill", "Bills", 92, False),
    ("water bill", "Bills", 90, False),
    ("gas bill", "Bills", 90, False),
    ("bills", "Bills", 75, False),
    ("utility", "Bills", 78, False),
    ("recharge", "Bills", 75, False),
    ("mobile", "Bills", 65, False),
    ("internet", "Bills", 75, False),
    ("insurance", "Bills", 70, False),
    ("property tax", "Bills", 85, False),
    ("municipal", "Bills", 80, False),

    # ── Entertainment ─────────────────────────────────────
    ("pvr", "Entertainment", 95, True),
    ("inox", "Entertainment", 95, True),
    ("bookmyshow", "Entertainment", 95, True),
    ("book my show", "Entertainment", 95, True),
    ("multiplex", "Entertainment", 85, False),
    ("cinema", "Entertainment", 80, False),
    ("movie", "Entertainment", 75, False),
    ("amazon prime", "Entertainment", 88, True),
    ("hotstar", "Entertainment", 88, True),
    ("disney", "Entertainment", 85, True),
    ("zee5", "Entertainment", 85, True),
    ("sony liv", "Entertainment", 85, True),
    ("spotify", "Entertainment", 90, True),
    ("apple music", "Entertainment", 88, True),
    ("youtube", "Entertainment", 80, True),
    ("youtube premium", "Entertainment", 88, True),
    ("steam", "Entertainment", 90, True),
    ("playstation", "Entertainment", 90, True),
    ("xbox", "Entertainment", 88, True),
    ("nintendo", "Entertainment", 88, True),
    ("pubg", "Entertainment", 85, True),
    ("valorant", "Entertainment", 85, True),
    ("dream11", "Entertainment", 88, True),
    ("my11circle", "Entertainment", 85, True),
    ("gaming", "Entertainment", 75, False),
    ("concert", "Entertainment", 80, False),
    ("entertainment", "Entertainment", 70, False),

    # ── Healthcare ────────────────────────────────────────
    ("apollo", "Healthcare", 90, True),
    ("fortis", "Healthcare", 90, True),
    ("max hospital", "Healthcare", 90, True),
    ("medanta", "Healthcare", 90, True),
    ("pharmeasy", "Healthcare", 92, True),
    ("netmeds", "Healthcare", 92, True),
    ("1mg", "Healthcare", 92, True),
    ("practo", "Healthcare", 88, True),
    ("lybrate", "Healthcare", 85, True),
    ("manipal", "Healthcare", 85, True),
    ("thyrocare", "Healthcare", 85, True),
    ("healthian", "Healthcare", 80, True),
    ("dr lal", "Healthcare", 85, True),
    ("hospital", "Healthcare", 80, False),
    ("clinic", "Healthcare", 78, False),
    ("doctor", "Healthcare", 75, False),
    ("medicine", "Healthcare", 78, False),
    ("pharmacy", "Healthcare", 80, False),
    ("health", "Healthcare", 70, False),
    ("diagnostic", "Healthcare", 80, False),
    ("lab test", "Healthcare", 82, False),
    ("dental", "Healthcare", 80, False),
    ("eye check", "Healthcare", 75, False),
    ("optical", "Healthcare", 75, False),

    # ── Education ─────────────────────────────────────────
    ("udemy", "Education", 95, True),
    ("coursera", "Education", 95, True),
    ("byju's", "Education", 93, True),
    ("byjus", "Education", 93, True),
    ("unacademy", "Education", 93, True),
    ("vedantu", "Education", 90, True),
    ("simplilearn", "Education", 88, True),
    ("upgrad", "Education", 88, True),
    ("edx", "Education", 90, True),
    ("udacity", "Education", 90, True),
    ("great learning", "Education", 88, True),
    ("pw", "Education", 85, True),
    ("physics wallah", "Education", 90, True),
    ("classplus", "Education", 82, True),
    ("skillshare", "Education", 85, True),
    ("masterclass", "Education", 85, True),
    ("nptel", "Education", 88, True),
    ("college", "Education", 75, False),
    ("university", "Education", 75, False),
    ("school", "Education", 75, False),
    ("tuition", "Education", 78, False),
    ("course", "Education", 70, False),
    ("education", "Education", 70, False),
    ("exam", "Education", 72, False),
    ("books", "Education", 65, False),
    ("library", "Education", 70, False),

    # ── Salary ────────────────────────────────────────────
    ("salary", "Salary", 95, False),
    ("payroll", "Salary", 95, False),
    ("wages", "Salary", 92, False),
    ("stipend", "Salary", 92, False),
    ("compensation", "Salary", 90, False),
    ("paycheck", "Salary", 90, False),

    # ── Investment ────────────────────────────────────────
    ("zerodha", "Investment", 95, True),
    ("angel broking", "Investment", 93, True),
    ("groww", "Investment", 93, True),
    ("upstox", "Investment", 93, True),
    ("icici direct", "Investment", 90, True),
    ("hdfc sec", "Investment", 88, True),
    ("motilal oswal", "Investment", 90, True),
    ("sharekhan", "Investment", 88, True),
    ("sbi mutual", "Investment", 88, True),
    ("paytm money", "Investment", 85, True),
    ("coin", "Investment", 80, True),
    ("kuvera", "Investment", 88, True),
    ("smallcase", "Investment", 88, True),
    ("mutual fund", "Investment", 88, False),
    ("sip", "Investment", 85, False),
    ("nps", "Investment", 85, False),
    ("ppf", "Investment", 85, False),
    ("fd", "Investment", 80, False),
    ("fixed deposit", "Investment", 85, False),
    ("stock", "Investment", 80, False),
    ("stocks", "Investment", 80, False),
    ("investment", "Investment", 75, False),
    ("dividend", "Investment", 80, False),
    ("bonds", "Investment", 78, False),
    ("etf", "Investment", 82, False),

    # ── Rent ──────────────────────────────────────────────
    ("rent", "Rent", 88, False),
    ("rental", "Rent", 85, False),
    ("lease", "Rent", 82, False),
    ("landlord", "Rent", 80, False),

    # ── Transfer ──────────────────────────────────────────
    ("fund transfer", "Transfer", 85, False),
    ("imps", "Transfer", 85, False),
    ("neft", "Transfer", 85, False),
    ("rtgs", "Transfer", 85, False),
    ("upi transfer", "Transfer", 82, False),
    ("bank transfer", "Transfer", 80, False),
    ("internal transfer", "Transfer", 82, False),
    ("self transfer", "Transfer", 85, False),
    ("to savings", "Transfer", 80, False),
    ("to current", "Transfer", 80, False),

    # ── ATM ───────────────────────────────────────────────
    ("atm", "ATM", 92, False),
    ("atm withdrawal", "ATM", 95, False),
    ("cash withdrawal", "ATM", 90, False),
    ("withdrawal", "ATM", 80, False),
    ("cash at", "ATM", 85, False),
    ("wdl", "ATM", 85, False),

    # ── Payment-mode hints (lower confidence) ─────────────
    ("upi", "Transfer", 65, False),
    ("wallet", "Transfer", 60, False),
    ("paytm", "Transfer", 60, True),
    ("google pay", "Transfer", 60, True),
    ("gpay", "Transfer", 60, True),
    ("phonepe", "Transfer", 60, True),
    ("amazon pay", "Transfer", 60, True),
]


def get_rules() -> list[tuple[str, str, int, bool]]:
    return RULES
